/**
 * Plugin storage document shapes for commerce (stage-1 vertical slice).
 * Field names use camelCase so they match indexed JSON paths.
 */

import type { OrderPaymentPhase } from "./kernel/finalize-decision.js";

export type { OrderPaymentPhase };

export interface CartLineItem {
	/**
	 * Stable catalog reference. Human-readable titles and `shortDescription` for
	 * embeddings live on the product document, not on this row.
	 */
	productId: string;
	/** Empty string when the catalog does not use variants. */
	variantId?: string;
	quantity: number;
	/** Inventory version captured when the line was last mutated (optimistic finalize). */
	inventoryVersion: number;
	unitPriceMinor: number;
}

export interface StoredCart {
	currency: string;
	lineItems: CartLineItem[];
	/**
	 * SHA-256 hex of the owner token issued at cart creation.
	 * Reads (`cart/get`) and mutations (`cart/upsert`) must present the matching raw token.
	 */
	ownerTokenHash: string;
	createdAt: string;
	updatedAt: string;
}

export interface OrderLineItem {
	snapshot?: OrderLineItemSnapshot;
	/** Catalog id for historical order display. */
	productId: string;
	variantId?: string;
	quantity: number;
	inventoryVersion: number;
	unitPriceMinor: number;
}

export interface OrderLineItemOptionSelection {
	attributeId: string;
	attributeValueId: string;
}

export interface OrderLineItemImageSnapshot {
	linkId: string;
	assetId: string;
	provider: string;
	externalAssetId: string;
	fileName?: string;
	altText?: string;
}

export interface OrderLineItemDigitalEntitlementSnapshot {
	entitlementId: string;
	digitalAssetId: string;
	digitalAssetLabel?: string;
	grantedQuantity: number;
	downloadLimit?: number;
	downloadExpiryDays?: number;
	isManualOnly: boolean;
	isPrivate: boolean;
}

export interface OrderLineItemBundleComponentSummary {
	componentId: string;
	componentSkuId: string;
	componentSkuCode: string;
	componentProductId: string;
	componentPriceMinor: number;
	quantityPerBundle: number;
	subtotalContributionMinor: number;
	availableBundleQuantity: number;
	/**
	 * Component SKU stock `version` captured at checkout for optimistic finalize.
	 * Missing or negative values indicate an incomplete bundle snapshot and should
	 * fail finalize reconciliation.
	 */
	componentInventoryVersion: number;
}

export interface OrderLineItemBundleSummary {
	productId: string;
	subtotalMinor: number;
	discountType: BundleDiscountType;
	discountValueMinor: number;
	discountValueBps: number;
	discountAmountMinor: number;
	finalPriceMinor: number;
	availability: number;
	components: OrderLineItemBundleComponentSummary[];
}

export interface OrderLineItemSnapshot {
	productId: string;
	skuId: string;
	productType: ProductType;
	productTitle: string;
	productSlug?: string;
	skuCode: string;
	selectedOptions: OrderLineItemOptionSelection[];
	currency: string;
	unitPriceMinor: number;
	compareAtPriceMinor?: number;
	lineSubtotalMinor: number;
	lineDiscountMinor: number;
	lineTotalMinor: number;
	requiresShipping: boolean;
	isDigital: boolean;
	image?: OrderLineItemImageSnapshot;
	bundleSummary?: OrderLineItemBundleSummary;
	digitalEntitlements?: OrderLineItemDigitalEntitlementSnapshot[];
}

export interface StoredOrder {
	cartId: string;
	paymentPhase: OrderPaymentPhase;
	currency: string;
	lineItems: OrderLineItem[];
	totalMinor: number;
	/**
	 * SHA-256 hex of the finalize token generated by checkout.
	 * Webhook finalize and order reads must present the matching raw token (e.g. copied from
	 * PaymentIntent metadata) or verification fails.
	 */
	finalizeTokenHash: string;
	createdAt: string;
	updatedAt: string;
}

export type PaymentAttemptStatus = "pending" | "succeeded" | "failed";

export interface StoredPaymentAttempt {
	orderId: string;
	providerId: string;
	status: PaymentAttemptStatus;
	externalRef?: string;
	createdAt: string;
	updatedAt: string;
}

export type WebhookReceiptStatus = "processed" | "duplicate" | "pending" | "error";

export type WebhookReceiptErrorCode =
	| "ORDER_NOT_FOUND"
	| "ORDER_STATE_CONFLICT"
	| "INVENTORY_CHANGED"
	| "INSUFFICIENT_STOCK"
	| "PRODUCT_UNAVAILABLE"
	| "VARIANT_UNAVAILABLE";

export type WebhookReceiptClaimState = "unclaimed" | "claimed" | "released";

export interface StoredWebhookReceipt {
	providerId: string;
	externalEventId: string;
	orderId: string;
	status: WebhookReceiptStatus;
	correlationId?: string;
	createdAt: string;
	updatedAt: string;
	/** Optional terminal error classification for operational triage and recovery tooling. */
	errorCode?: WebhookReceiptErrorCode;
	/** Optional operational details for terminal error receipts. */
	errorDetails?: Record<string, unknown>;
	/** Lease owner for concurrency recovery / claim transfer. */
	claimOwner?: string;
	/** Lease token tied to a claim attempt (opaque to storage layer). */
	claimToken?: string;
	/** Lease expiry timestamp (ISO-8601 string) for stale-claim recovery. */
	claimExpiresAt?: string;
	/** Storage version observed when claim token was issued (for CAS-style transitions). */
	claimVersion?: string;
	/** High-level state of claim ownership (`claimed` when actively owned). */
	claimState?: WebhookReceiptClaimState;
}

export interface StoredIdempotencyKey {
	route: string;
	keyHash: string;
	httpStatus: number;
	responseBody: unknown;
	createdAt: string;
}

/** Append-only movement row; materialized quantity lives in {@link StoredInventoryStock}. */
export interface StoredInventoryLedgerEntry {
	productId: string;
	/** Empty string when the catalog does not use variants. */
	variantId: string;
	delta: number;
	referenceType: string;
	referenceId: string;
	createdAt: string;
}

export interface StoredInventoryStock {
	productId: string;
	variantId: string;
	version: number;
	quantity: number;
	updatedAt: string;
}

export type ProductType = "simple" | "variable" | "bundle";
export type ProductStatus = "draft" | "active" | "archived";
export type ProductVisibility = "public" | "hidden";
export type ProductSkuStatus = "active" | "inactive";
export type BundleDiscountType = "none" | "fixed_amount" | "percentage";
export type ProductSkuLifecycleState = "valid" | "requires_review" | "auto_paused" | "reconciled";

export interface StoredProduct {
	id: string;
	type: ProductType;
	status: ProductStatus;
	visibility: ProductVisibility;
	slug: string;
	/** Canonical storefront slug (kept on the main product row for fast reads). */
	currentSlug?: string;
	title: string;
	shortDescription: string;
	longDescription: string;
	brand?: string;
	vendor?: string;
	featured: boolean;
	sortOrder: number;
	requiresShippingDefault: boolean;
	taxClassDefault?: string;
	metadataJson?: Record<string, unknown>;
	bundleDiscountType?: BundleDiscountType;
	bundleDiscountValueMinor?: number;
	bundleDiscountValueBps?: number;
	createdAt: string;
	updatedAt: string;
	publishedAt?: string;
	archivedAt?: string;
}

export interface StoredProductSlugHistory {
	productId: string;
	/** Historical slug that is no longer the product's active `slug/currentSlug`. */
	slug: string;
	createdAt: string;
	replacedBy?: string;
}

export interface StoredProductSku {
	id: string;
	productId: string;
	skuCode: string;
	status: ProductSkuStatus;
	lifecycleState?: ProductSkuLifecycleState;
	lifecycleStateUpdatedAt?: string;
	lifecycleStateReason?: string;
	unitPriceMinor: number;
	compareAtPriceMinor?: number;
	inventoryQuantity: number;
	inventoryVersion: number;
	requiresShipping: boolean;
	isDigital: boolean;
	createdAt: string;
	updatedAt: string;
}

export type ProductAttributeKind = "variant_defining" | "descriptive";

export interface StoredProductAttribute {
	id: string;
	productId: string;
	name: string;
	code: string;
	kind: ProductAttributeKind;
	position: number;
	createdAt: string;
	updatedAt: string;
}

export interface StoredProductAttributeValue {
	id: string;
	attributeId: string;
	value: string;
	code: string;
	position: number;
	createdAt: string;
	updatedAt: string;
}

export interface StoredProductSkuOptionValue {
	id: string;
	skuId: string;
	attributeId: string;
	attributeValueId: string;
	createdAt: string;
	updatedAt: string;
}

export interface StoredDigitalAsset {
	id: string;
	provider: string;
	externalAssetId: string;
	label?: string;
	downloadLimit?: number;
	downloadExpiryDays?: number;
	isManualOnly: boolean;
	isPrivate: boolean;
	createdAt: string;
	updatedAt: string;
	metadata?: Record<string, unknown>;
}

export interface StoredDigitalEntitlement {
	id: string;
	skuId: string;
	digitalAssetId: string;
	grantedQuantity: number;
	createdAt: string;
	updatedAt: string;
}

export interface StoredCategory {
	id: string;
	name: string;
	slug: string;
	parentId?: string;
	position: number;
	createdAt: string;
	updatedAt: string;
}

export interface StoredProductCategoryLink {
	id: string;
	productId: string;
	categoryId: string;
	createdAt: string;
	updatedAt: string;
}

export interface StoredProductTag {
	id: string;
	name: string;
	slug: string;
	createdAt: string;
	updatedAt: string;
}

export interface StoredProductTagLink {
	id: string;
	productId: string;
	tagId: string;
	createdAt: string;
	updatedAt: string;
}

export interface StoredBundleComponent {
	id: string;
	bundleProductId: string;
	componentSkuId: string;
	quantity: number;
	position: number;
	createdAt: string;
	updatedAt: string;
}

export type ProductAssetLinkTarget = "product" | "sku";

export type ProductAssetRole = "primary_image" | "gallery_image" | "variant_image";

export interface StoredProductAsset {
	id: string;
	provider: string;
	externalAssetId: string;
	fileName?: string;
	altText?: string;
	mimeType?: string;
	byteSize?: number;
	width?: number;
	height?: number;
	createdAt: string;
	updatedAt: string;
	metadata?: Record<string, unknown>;
}

export interface StoredProductAssetLink {
	id: string;
	targetType: ProductAssetLinkTarget;
	targetId: string;
	assetId: string;
	role: ProductAssetRole;
	position: number;
	createdAt: string;
	updatedAt: string;
}
